#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_TesteTec
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Teste_DataBase")]
	public partial class DataClasseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    #endregion
		
		public DataClasseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Teste_DataBaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CLI_ID;
		
		private string _CLI_NOME;
		
		private System.DateTime _CLI_DATANASCIMENTO;
		
		private bool _CLI_ATIVO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCLI_IDChanging(int value);
    partial void OnCLI_IDChanged();
    partial void OnCLI_NOMEChanging(string value);
    partial void OnCLI_NOMEChanged();
    partial void OnCLI_DATANASCIMENTOChanging(System.DateTime value);
    partial void OnCLI_DATANASCIMENTOChanged();
    partial void OnCLI_ATIVOChanging(bool value);
    partial void OnCLI_ATIVOChanged();
    #endregion
		
		public Cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLI_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CLI_ID
		{
			get
			{
				return this._CLI_ID;
			}
			set
			{
				if ((this._CLI_ID != value))
				{
					this.OnCLI_IDChanging(value);
					this.SendPropertyChanging();
					this._CLI_ID = value;
					this.SendPropertyChanged("CLI_ID");
					this.OnCLI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLI_NOME", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string CLI_NOME
		{
			get
			{
				return this._CLI_NOME;
			}
			set
			{
				if ((this._CLI_NOME != value))
				{
					this.OnCLI_NOMEChanging(value);
					this.SendPropertyChanging();
					this._CLI_NOME = value;
					this.SendPropertyChanged("CLI_NOME");
					this.OnCLI_NOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLI_DATANASCIMENTO", DbType="Date NOT NULL")]
		public System.DateTime CLI_DATANASCIMENTO
		{
			get
			{
				return this._CLI_DATANASCIMENTO;
			}
			set
			{
				if ((this._CLI_DATANASCIMENTO != value))
				{
					this.OnCLI_DATANASCIMENTOChanging(value);
					this.SendPropertyChanging();
					this._CLI_DATANASCIMENTO = value;
					this.SendPropertyChanged("CLI_DATANASCIMENTO");
					this.OnCLI_DATANASCIMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLI_ATIVO", DbType="Bit NOT NULL")]
		public bool CLI_ATIVO
		{
			get
			{
				return this._CLI_ATIVO;
			}
			set
			{
				if ((this._CLI_ATIVO != value))
				{
					this.OnCLI_ATIVOChanging(value);
					this.SendPropertyChanging();
					this._CLI_ATIVO = value;
					this.SendPropertyChanged("CLI_ATIVO");
					this.OnCLI_ATIVOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
